[project]
name = "fastmcp-sample"
version = "0.1.0"
description = "FastMCP sample project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.118.0",
    "fastmcp>=2.12.4",
]
